CREATE DATABASE TareaObjetoRelacional;

--Tipos
CREATE TYPE Autor AS(--Listo
    nombre varchar (100),
    alias varchar(100)
);
CREATE TYPE Direccion AS(--Listo
    provincia varchar(30) ,
    canton varchar(30) ,
    distrito varchar(30) ,
    linkGoogleMaps varchar(250)
);
CREATE TYPE Persona AS(--Listo
    numeroCedula integer,
    nombre varchar(20),
    apellidos varchar(20) array[3],
    fechaNacimiento date,
    correos varchar(100) array[2],
    telefonos varchar(10) array[2]
);
--Suponiendo que la tienda física vende discos físicos.
CREATE TYPE Producto AS(--Listo
    idProducto int,
    cantidad int,
    precio money,
    nombre varchar(30),
    autores Autor array[10],
    descripcion varchar(30) array[10],
    categorias varchar(30) array[5]
);
CREATE TYPE Proveedor AS(--Listo
    idProvedor int,
    nombre varchar(30),
    direccion Direccion,
    productos Producto array[50]
);
--Tablas
CREATE TABLE Cliente(--Listo
    idCliente int GENERATED BY DEFAULT AS IDENTITY primary key not null,
    datosPersonales Persona not null
);
CREATE TABLE Empleado(--Listo
    idEmpleado int GENERATED BY DEFAULT AS IDENTITY primary key not null,
    datosPersonales Persona not null
);
CREATE TABLE Venta(--Listo
    idVenta int GENERATED BY DEFAULT AS IDENTITY primary key not null,
    idEmpleado int not null,
    idCliente int not null,
    costo money,
    productos Producto array[10],

    CONSTRAINT fk_idEmpleado FOREIGN KEY (idEmpleado) REFERENCES Empleado(idEmpleado),
    CONSTRAINT fk_idCliente FOREIGN KEY (idCliente) REFERENCES Cliente(idCliente)
);
--Cambie esta tabla porque el precio y cantidad deberia poder cambiarse
CREATE TABLE Productos(
    producto Producto not null,
    precio money not null,
    cantidad int not null --Unidades en stock
);
--CREATE TABLE Productos of Producto;--Listo
CREATE TABLE Proveedores of Proveedor;--Listo
--CREATE TABLE Autores of Autor;--Listo, esta tabla no se usa, siempre se meten los objetos autor en el array de producto.


/* PRUEBAS

INSERT INTO public.productos(
	idproducto, cantidad, precio, nombre, autores, descripcion, categorias)
	VALUES (1,10,2500,'Pure Vibez', array[('Pietro','DJ P')::autor]
			,'{Album musica urbana,Musica criminal}',
		   '{Dancehall,Reggae,Rap}');--Sirve
INSERT INTO public.productos(
	idproducto, cantidad, precio, nombre, autores, descripcion, categorias)
	VALUES (2,20,5000,'Kid A', array[('El saico','Solo pinga')::autor,
									 ('El otro man','cp feo')::autor]
			,'{Probando arrays, otra prueba feo,otro mas}',
		   '{no pues, me mame, jaja}');--Sirve		   
		  
		   
select * from productos;--Funciona
select autores[1].nombre from productos;--Funciona

update Productos set precio=1 where idProducto=1;--Sirve
	
insert into public.autores(nombre,alias) values ('Toledo','Toledo');--Funciona bien
select * from Autores;


*/